version: "3.9"

services:
    db:
        image: postgres:14
        container_name: quiz_app_db
        environment: 
            - POSTGRES_DB=quiz_app
            - POSTGRES_USER=quiz_app
            - POSTGRES_PASSWORD=secret
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
    quiz_app:
        container_name: quiz_app_backend
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./quiz_app:/quiz_app
        environment: 
            - DB_HOST=db
            - DB_NAME=quiz_app
            - DB_USER=quiz_app
            - DB_PASS=secret
            - DB_PORT=5432
        entrypoint: /docker-entrypoint.sh
        depends_on:
            db:
                condition: service_healthy
