name: QuizApp CI

on:
  pull_request:
    branches: [ "main" ]
    inputs:
      test:
        description: 'Run pytest'
        type: boolean
        required: true
        default: true
      lint:
        description: 'Run black check'
        type: boolean
        required: true
        default: true
  workflow_dispatch:
    inputs:
      test:
        description: 'Run pytest'
        type: boolean
        required: true
        default: true
      lint:
        description: 'Run black check'
        type: boolean
        required: true
        default: true


jobs:
  build:
    name: Lint and test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: quiz_app
          POSTGRES_USER: quiz_app
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
    env:
      DB_HOST: localhost
      DB_NAME: quiz_app
      DB_USER: quiz_app
      DB_PASS: secret
      DB_PORT: 5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-interaction
    - name: Run migrations
      run: poetry run python manage.py migrate
      working-directory: ./quiz_app     
    - name: Run Tests
      run: poetry run pytest
      if: ${{ github.event.inputs.test }}
      working-directory: ./quiz_app
    - name: Run linter
      run: poetry run black --check .
      if: ${{ github.event.inputs.lint }}
      working-directory: ./quiz_app
