name: QuizApp CI

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    uses: ./.github/workflows/backend.yml
  ci:
    name: Lint and test
    needs: [ backend ]
    steps: 
      - name: Run Tests
        run: poetry run pytest
        working-directory: ./quiz_app
      - name: Run linter
        run: poetry run black --check .
        working-directory: ./quiz_app
